//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JokeGenerator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Why can\'t a bicycle stand on its own? Because it\'s too tired.</string>\r\n  " +
            "<string>What goes up and down but does not move? Stairs.</string>\r\n  <string>Whe" +
            "re should a 500 pound alien go? On a diet.</string>\r\n  <string>What did one toil" +
            "et say to the other? You look a bit flushed.</string>\r\n  <string>Why was the sta" +
            "dium so hot? Because all the fans left.</string>\r\n  <string>Why can\'t zoo animal" +
            "s take tests? Too many Cheetahs.</string>\r\n  <string>What do you call a fibbing " +
            "feline? A lion.</string>\r\n  <string>What\'s small, green, and goes up &amp; down?" +
            " A pea in an elevator.</string>\r\n  <string>What\'s a parrot\'s favorite kind of di" +
            "p? Squacamole.</string>\r\n  <string>What did the police officer say to their bell" +
            "y button? \"You\'re under a vest.\"</string>\r\n  <string>What did one ocean say to t" +
            "he other ocean? Nothing, they just waved.</string>\r\n  <string>What did the paper" +
            " say to the pencil? \"Write on!\"</string>\r\n  <string>Why did the picture go to ja" +
            "il? Because it was framed.</string>\r\n  <string>What did one wall say to the othe" +
            "r wall? \"I\'ll meet you at the corner.\"</string>\r\n  <string>What do you call a bo" +
            "y named Lee that no one talks to? Lonely.</string>\r\n  <string>What did Cinderell" +
            "a say when her photos didn\'t show up? \"Someday my prints will come!\"</string>\r\n " +
            " <string>Why was the broom late? It over swept!</string>\r\n  <string>Why couldn\'t" +
            " the pirate play cards? Because he was sitting on the deck.</string>\r\n  <string>" +
            "Why was everyone so tired on April 1st? Because they just had a March of 31 days" +
            ".</string>\r\n  <string>Why can\'t your nose be 12 inches long? Because then it wou" +
            "ld be a foot.</string>\r\n  <string>What U.S. state has the smallest pop cans? Min" +
            "nisota.</string>\r\n  <string>What\'s green and has wheels? Grass, I lied about the" +
            " wheels.</string>\r\n  <string>What\'s blue and fluffy? Blue fluff.</string>\r\n  <st" +
            "ring>What\'s brown and sticky? A stick.</string>\r\n  <string>What do you call a Pu" +
            "erto Rican flying an airplane? A pilot.</string>\r\n  <string>Why did Billy fall o" +
            "ff of his bike? Billy was a potato.</string>\r\n  <string>What\'s red and smells li" +
            "ke blue paint? Red paint.</string>\r\n  <string>Why did Billy go out with a prune?" +
            " Because he couldn\'t find a date.</string>\r\n  <string>How do you find Will Smith" +
            " in the snow? You look for the fresh prints.</string>\r\n  <string>Why did the hip" +
            "ster burn his tongue? He drank his coffee before it was cool.</string>\r\n  <strin" +
            "g>How do you top a car? Tep on the brake, tupid. </string>\r\n  <string>What do yo" +
            "u call cheese that\'s not yours? Nacho cheese.</string>\r\n  <string>What do you ge" +
            "t when you put a candle into a suit of armor? A knight light.</string>\r\n  <strin" +
            "g>A sheep, a drum, and a snake fall off of a cliff. Ba-Dum-Tss.</string>\r\n  <str" +
            "ing>Did you hear about the two peanuts walking down the alley? One was a salted." +
            " </string>\r\n  <string>What do you call a cow with two legs? Lean beef.</string>\r" +
            "\n  <string>What do you call a deer with no eyes? No idear.</string>\r\n  <string>W" +
            "hat do you call a deer with no eyes and no legs? Still no idear.</string>\r\n  <st" +
            "ring>The past, present, and future walk into a bar. It was tense.</string>\r\n  <s" +
            "tring>An Irishman walks past a bar.</string>\r\n  <string>What goes *click click c" +
            "lick* \"Did I get it?\" Stevie Wonder doing a Rubik\'s cube.</string>\r\n  <string>Wh" +
            "at did the grape say when it was pinched? Nothing, it just gave out a little whi" +
            "ne.</string>\r\n  <string>How do you make a tissue dance? You put a little boogie " +
            "in it.</string>\r\n  <string>Why can\'t you hear a pterodactyl in the bathroom? Bec" +
            "ause it has a silent pee.</string>\r\n  <string>Why did the Storm Trooper buy and " +
            "iPhone? Because he couldn\'t find the Droid he was looking for.</string>\r\n  <stri" +
            "ng>Why was six afraid of seven? Because seven ate nine.</string>\r\n  <string>Why " +
            "was seven afraid of eight? Because eight was a six offender. </string>\r\n  <strin" +
            "g>This is an A and B conversasion. C your way out of it, before D and E F you up" +
            ".</string>\r\n  <string>How does Moses make coffee? He brews it.</string>\r\n  <stri" +
            "ng>Where does a sheep go for a haircut? The baaa baaa shop.</string>\r\n  <string>" +
            "What do you do with a dead chemist? You Barium.</string>\r\n  <string>What do you " +
            "call a sleepwalking nun? A roamin\' Catholic.</string>\r\n  <string>What did 0 say " +
            "to 8? \"Nice belt!\"</string>\r\n  <string>Why did the orange stop? Because it ran o" +
            "utta juice.</string>\r\n  <string>What\'s the last thing that goes through a bug\'s " +
            "mind when it hits the windshield? His butt.</string>\r\n  <string>When do you put " +
            "a cow on an elevator? When you want to raise the steaks!</string>\r\n</ArrayOfStri" +
            "ng>")]
        public global::System.Collections.Specialized.StringCollection JokeList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["JokeList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LikeOrDislike {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LikeOrDislike"]));
            }
            set {
                this["LikeOrDislike"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentJoke {
            get {
                return ((int)(this["CurrentJoke"]));
            }
            set {
                this["CurrentJoke"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
  <string>0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection JokeSeen {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["JokeSeen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>I have a medical appointment at 10:30am tomorrow in Boulder and will be ar" +
            "riving late, probably a bit after noon.</string>\r\n  <string>I’m not feeling grea" +
            "t, and I’m going to have to leave after the sprint retrospective (2:30 PM) for a" +
            " second medical appointment.  I will be online again working from home a bit thi" +
            "s evening though.</string>\r\n  <string>I have a late afternoon medical appointmen" +
            "t and will be leaving early today at 3 PM.</string>\r\n  <string>I got in a bit la" +
            "ter than expected, so not sure what time I\'ll be coming in.... I\'ll send out ano" +
            "ther email once I\'m rested up and on my way.</string>\r\n  <string>I will be comin" +
            "g in late today because I will be going on a trip out of town over the weekend a" +
            "nd flying back on a red eye flight.  I should be in the office by noon.</string>" +
            "\r\n  <string>I\'ve sliced a good bit into my fingertip with a sharp knife. I can g" +
            "et it to calm down for short bursts but it keeps breaking open and bleeding all " +
            "over again. I\'m going to head to a doctor for what I\'m guessing will be stitches" +
            ". That means I\'m wfh today.</string>\r\n  <string>I\'m still feeling a bit sick wit" +
            "h a cold or flu and I have no meetings today, so I\'ll be working from home.  You" +
            " can reach me on Teams or on my Google Voice.</string>\r\n  <string>I’m probably g" +
            "oing to have to start working later than usual again tomorrow, as I’m still feel" +
            "ing little bit sick, and may need some extra rest again tomorrow (I ended up hav" +
            "ing to sleep in until 9:30 AM today).  I’ll probably be working remotely or in t" +
            "he office by late morning – around 11 AM.   I’ll send out any updates tomorrow.<" +
            "/string>\r\n  <string>I woke up much earlier than yesterday, and I\'m doing better," +
            " but I\'m still a bit run down, so I\'m going to work from home today (unless ther" +
            "e\'s some need for me to come in).  I should be starting around 10 AM, after stan" +
            "dups. </string>\r\n  <string>I’m feeling well enough to come in and will be in the" +
            " office this afternoon (by 1 PM).</string>\r\n  <string>I’m online now, working re" +
            "motely while I grab some breakfast and trying to figure out if I’ll be able to m" +
            "ake it in to the office later.</string>\r\n  <string>I\'m feeling sick and feel lik" +
            "e I need some extra rest, so I\'m going to sleep in and probably start working la" +
            "ter today. We\'ll see if I can come in to the office or have to work remotely.</s" +
            "tring>\r\n  <string>I’m not feeling well, and I’m going to have to head home after" +
            " I get out of the meeting.  I will work from home later.</string>\r\n  <string>I w" +
            "as still feeling a bit sick with a cough and needed some extra rest this morning" +
            ", so I\'ll be coming in late today. I\'m going to try to make it in time for the p" +
            "resentation at 11.</string>\r\n  <string>I didn’t quite make it out in time, so I’" +
            "m going to call in to the Meeting and come in to the office afterwards (at 1 PM)" +
            ".</string>\r\n  <string>I’m still feeling sick and have a mid-afternoon medical ap" +
            "pointment today, so I’ll be working from home.  I’ll be leaving for my appointme" +
            "nt at 1:45 PM, back from that at maybe 4 PM.</string>\r\n  <string>I am still feel" +
            "ing a bit sick and did\'t get enough sleep last night....  I\'ll be coming in late" +
            " this morning.</string>\r\n  <string>I am going try to work from home, because I\'m" +
            " really not feeling well, but I am completely locked out of my laptop after sett" +
            "ing a new password.  Neither the old password nor the new one work.  I have a Se" +
            "rvice ticket open, and I may have to come in to get things unlocked.</string>\r\n " +
            " <string>I am in the office now.  I could not get my laptop to unlock without co" +
            "ming in.</string>\r\n  <string>I have a medical appointment and will be leaving ea" +
            "rly today at 3 PM.</string>\r\n  <string>I have a medical appointment in Boulder a" +
            "nd will be out of the office this afternoon, from about 12 noon to 3:30 PM.</str" +
            "ing>\r\n  <string>I’m not feeling well (I’ve come down with cough) and got woken u" +
            "p early this morning, so I’m going to head home to rest a bit and hopefully work" +
            " from home later. </string>\r\n  <string>I will be out of the office this afternoo" +
            "n, starting at 1:30 PM, due to medical appointments.  I should be home briefly b" +
            "etween the two appointments, around 4 PM, and I’ll be online for a bit to respon" +
            "d to emails, etc.</string>\r\n  <string>I’m still feeling sick, and I’m not going " +
            "to make it out in time for review, so I’m just going to call in and work remotel" +
            "y again today.</string>\r\n  <string>I had a bout of insomnia last night and feel " +
            "like I’m coming down with a cold now, so I’m going to head home and rest.  I’ll " +
            "work from home later, as I’m able to.</string>\r\n  <string>I will be on vacation " +
            "in New Orleans for Halloween.</string>\r\n  <string>I will be leaving early for a " +
            "medical appointment.</string>\r\n  <string>I will be leaving at 3:30 PM today for " +
            "a medical appointment.</string>\r\n  <string>I have my replacement license plates " +
            "now, but this is a total pain – I cannot mount them, because the thieves who too" +
            "k off with my front plate took the mountain bracket as well, and the old rear pl" +
            "ate will not come off, so I now have to go to the nearest Subaru dealership to d" +
            "eal with that, so I can drive my vehicle legally.  I’m going to grab my lunch an" +
            "d then head down there….  Hopefully I’ll be back in the office later this aftern" +
            "oon.</string>\r\n  <string>Just an update – I am now in the office, but this took " +
            "forever, because the Subaru dealership could not remove the rear license plate a" +
            "nd had to go to a body shop to get the screws out.  I had to go all over the pla" +
            "ce nad didn’t get to stop anywhere long enough to eat, so I’m going to grab lunc" +
            "h now and may be away from my desk.</string>\r\n  <string>I have a furniture deliv" +
            "ery coming today, so I will be working remotely.</string>\r\n  <string>Someone sto" +
            "le my front license plate, and I need to go to the DMV to get a replacement firs" +
            "t thing tomorrow.  I’m not sure how long this will take.</string>\r\n  <string>My " +
            "flight back home last night was a bit delayed, and I got in late and didn’t have" +
            " time to do laundry, etc., so I will be coming in late this morning.</string>\r\n " +
            " <string>I will be on a short vacation in Seattle tomorrow.</string>\r\n  <string>" +
            "With these other appointments, I had to shift my usual time for physical therapy" +
            " exercises to 3 PM today, so I will be out of the office this afternoon.</string" +
            ">\r\n  <string>I have to see my dentist before my upcoming trip out of town, so I " +
            "will be out of the office tomorrow morning until about noon.</string>\r\n  <string" +
            ">I will be leaving early at 3:30 PM for a medical appointment.</string>\r\n  <stri" +
            "ng>I seem to be coming down with the same illness that some of my team members a" +
            "re sick with, cough and all, so I will be leaving early today.</string>\r\n  <stri" +
            "ng>There was some confusion and they can’t actually deliver most of my furniture" +
            " today….  So I’ll be in the office later after calling in, but I will have to wo" +
            "rk remotely.</string>\r\n  <string>I have a medical appointment this afternoon and" +
            " will be leaving at 1:45 PM.  I may be back later, depending on how long it runs" +
            ".</string>\r\n  <string>I have to head home for my lunch break, and I’m just going" +
            " to head to my medical appointment from there.  I’ll be stepping out in a bit an" +
            "d online for a little bit before I leave for my appointment.</string>\r\n  <string" +
            ">I need to see a different doctor for my foot and will be out of the office tomo" +
            "rrow morning. </string>\r\n  <string>I hurt my foot and need to go see a doctor to" +
            "morrow morning.</string>\r\n  <string>I’m running a bit late and had to stop back " +
            "home on my way back, so at this point, I’ll probably just be in after lunch (at " +
            "1 PM).</string>\r\n  <string>I’m not feeling well, and I’m going to have to work f" +
            "rom home at least for this morning….  I might come in later in the afternoon.  <" +
            "/string>\r\n  <string>I have a medical appointment this morning and will be out of" +
            " the office.  I am feeling better than the last two days and will be in the offi" +
            "ce after lunch though.</string>\r\n  <string>I’m still not feeling well, so I’ll b" +
            "e working from home for at least this morning.  I did get some things from my do" +
            "ctor to help with my symptoms, so hopefully I’ll be feeling better as the day go" +
            "es on.</string>\r\n  <string>I’m not feeling well and will be working from home fo" +
            "r the remainder of the day today. </string>\r\n  <string>I have a doctor’s appoint" +
            "ment from 11 AM to 1 PM, so I will be working from home this morning.  Also, I w" +
            "ill be on a camping vacation and unreachable starting tomorrow through next Mond" +
            "ay.</string>\r\n  <string>I will be working from home tomorrow, as I have handymen" +
            " coming back to finish up things, and this time I want to be there to supervise " +
            "them and make sure everything gets completed. </string>\r\n  <string>I have a medi" +
            "cal appointment tomorrow morning and will be working from home until about 10:45" +
            " AM. </string>\r\n  <string>I have a handyman coming to fix some things at my plac" +
            "e and will be working from home tomorrow.</string>\r\n  <string>As I mentioned bef" +
            "ore my trip, I will not be coming in until this afternoon, due to last night’s r" +
            "ed eye flight, probably a bit after grabbing brunch (around 1 PM).  I kind of sc" +
            "rewed up my back travelling, so I will just be in the office for a bit today, un" +
            "til around 3:30 PM, and then I will be leaving for a massage therapy appointment" +
            ".  </string>\r\n  <string>I will be out on vacation Tuesday and will also likely b" +
            "e in the office late on Wednesday, as I have a red eye flight back from my trip " +
            "the night before.</string>\r\n  <string>I have a medical appointment this afternoo" +
            "n and will be leaving the office around 1:45 PM.</string>\r\n  <string>I have hand" +
            "ymen coming back to finish up a bunch of repairs around the house, as well as ai" +
            "r conditioning service scheduled for tomorrow, and I may need to be there to sup" +
            "ervise, so I will be working from home.  </string>\r\n  <string>My back is totally" +
            " screwed up and I couldn’t get away for a massage therapy appointment during the" +
            " planning, so I’m going in this afternoon.</string>\r\n  <string>I have major plum" +
            "bing repairs happening tomorrow, and this may require my attention, so I will be" +
            " working from home. </string>\r\n  <string>Forgot to mention – I will also be away" +
            " for a medical appointment tomorrow around noon.</string>\r\n  <string>I need to b" +
            "e home for an electrical inspection and to meet plumbers at my place, so I will " +
            "be out of the office after 12 noon. </string>\r\n  <string>I have a medical appoin" +
            "tment this morning, and will be arriving late.</string>\r\n  <string>The electrica" +
            "l inspector is running late, so I may be working from home until around 4 PM (I’" +
            "m heading back downtown later, but may just go to the gym, depending on what tim" +
            "e the inspection is done).</string>\r\n  <string>I will be out of the office and t" +
            "his afternoon from about 12 noon to 3 PM for an electrical inspection and to mee" +
            "t someone for yard maintenance.  I’ll be working remotely after my lunch break.<" +
            "/string>\r\n  <string>I’m still feeling a bit run down with the cold, and I’m goin" +
            "g to be working from home today.  </string>\r\n  <string>I’m still sick with a col" +
            "d and might have gotten more sick from the lack of power (and heat) the night be" +
            "fore last….  I’m going to work from today. I may be off to a late start.</string" +
            ">\r\n  <string>Xcel is saying power has been restored to my area, and I’m feeling " +
            "sick, so I’m heading home, and I’m going to work remotely.  I’ll be back if powe" +
            "r isn’t really restored. </string>\r\n  <string>I\'m sick with a cold and and was g" +
            "oing to work from home today, but the winds knocked the power out at my place, a" +
            "nd I don\'t even have heat or hot water or way to keep my laptop charged, so I\'m " +
            "going to have to come in later....  I\'m running a bit late, due to this whole si" +
            "tuation.  I\'ll probably be in sometime later.</string>\r\n  <string>I have plumber" +
            "s coming this morning and will be out of the office until about noon. </string>\r" +
            "\n  <string>I’ve got a cold and I’m sneezing my head off, so I’m just going to wo" +
            "rk from home today.</string>\r\n  <string>I have plumbers coming back tomorrow mor" +
            "ning to continue troubleshooting a tricky issue, and I will be working from home" +
            ". </string>\r\n  <string>I have a medical appointment this afternoon, and I will b" +
            "e out of the office from about 1:00 PM to 3:30 PM.</string>\r\n  <string>I have to" +
            " go in for routine medical lab tests and will be out of the office this afternoo" +
            "n from 2:00 PM until maybe 3:30 PM today (if the lab is running on time).</strin" +
            "g>\r\n  <string>I have plumbers coming back again to follow up on some issues and " +
            "I will be leaving around 1:45 PM and working from home this afternoon.</string>\r" +
            "\n  <string>I’ve got a doctor’s appointment this morning, and I have either an is" +
            "sue with the plumbing or HVAC at my place, so I’m going to have the heating and " +
            "air people look at things later (after noon).  I’ll be in the office by 10:30 AM" +
            " and then leaving sometime after noon and working from home today.</string>\r\n  <" +
            "string>I’m just going to be in the office for a short while today, because I got" +
            " back in to town on a red eye flight last night (arriving home at 2 AM), and I’v" +
            "e got to see my osteopath for back issues this afternoon.  I’ll be in the office" +
            " soon, but I’ll be leaving around 1:45 PM.</string>\r\n  <string>I have a plumbing" +
            " issue and will be working from home after noon today.</string>\r\n  <string>I’ve " +
            "actually got a few more things to do to prepare for my trip before the plumbers " +
            "show up, and most people I’m working with seem to be working from home today, so" +
            " I’m just going to work from home for the day as well.</string>\r\n  <string>I hav" +
            "e a handyman here dealing with a few things, and I’ll be working from home this " +
            "morning.</string>\r\n  <string>Just a heads up I’m wfh today.</string>\r\n  <string>" +
            "I have window repairs taking place at my place (they didn’t have all the parts a" +
            "t my first appointment) and will be out of the office today.</string>\r\n  <string" +
            ">It looks like I’m not really needed in the office this afternoon, so I’m just g" +
            "oing to stay here and work from home. </string>\r\n  <string>I’m still feeling sic" +
            "k with the stomach bug, so I’m just going to get what I can done working from ho" +
            "me today.  I may be offline part of the time, as I may need some rest.</string>\r" +
            "\n  <string>I think I actually have the stomach virus that was going around, not " +
            "just a cold like I was thinking earlier, and I’ve got a lot going on with contra" +
            "ctors today, so I probably shouldn’t be in the office, and I’m just going to get" +
            " what I can done working remotely.  I will be online as much as I’m able to be (" +
            "I may need some rest).</string>\r\n  <string>I have some issues I need to discuss " +
            "with the contractors working on my basement, and I’m waiting for them to show up" +
            ", so I’m going to be coming late today.  I’m not sure what time.</string>\r\n  <st" +
            "ring>I’m going to have stay home a bit longer, until 11 AM or so, so I can meet " +
            "with one of the subcontractors who’s doing a different part of the work and get " +
            "everyone on the same page.</string>\r\n  <string>I have one of the last phases of " +
            "my basement remodel starting today, and I need to meet the construction crew her" +
            "e to make sure they can get in, as they had some trouble with the door code last" +
            " time.  I’ll probably be leaving for the office around 10 AM and may not be able" +
            " to call in, as that\'s around when they may arrive.</string>\r\n  <string>I have a" +
            " medical appointment this afternoon and will be heading out for that around 3:15" +
            " PM.</string>\r\n  <string>I have a window repair appointment this morning at 10 A" +
            "M, so I will be coming in to the office late.</string>\r\n  <string>Well, I didn’t" +
            " know this was a rolling window repair appointment between 10 and noon, and they" +
            " get here around noon, so I’m probably not going to be in until later in the aft" +
            "ernoon.</string>\r\n  <string>I’m actually still feeling a bit run down today, lik" +
            "e I might have a cold or something, so I’m just going to stay here and rest up a" +
            " bit and then try to get some more work done from home later.</string>\r\n  <strin" +
            "g>I’m feeling a bit run down, like I might be coming down with something, so I’m" +
            " going to head home, rest for a bit, and then work from home later. </string>\r\n " +
            " <string>I have routine medical lab tests scheduled tomorrow morning, and I may " +
            "be late and could miss meetings, depending on how long it takes.</string>\r\n  <st" +
            "ring>I had all sorts of delays getting home from the airport, due to the snow la" +
            "st night (landing, getting baggage, driving home), so I got in really late, and " +
            "I also threw my back out on the trip and need to get it adjusted by my osteopath" +
            " at noon today. </string>\r\n  <string>I have a PTO day tomorrow and will be out o" +
            "f town through President’s Day, but I need to take off a bit early today to fini" +
            "sh getting ready for my trip, so I’ll probably actually be working a bit on the " +
            "plane to make up for it (I will check my email sometime around noon and respond " +
            "to anything urgent.)</string>\r\n  <string>Due to a miscommunication, I wasted a b" +
            "unch of time going in to my doctor’s office today, when they actually had the ap" +
            "pointment down for tomorrow – so it will be the same deal as today: I’ll work fr" +
            "om home until 11 AM tomorrow, head to my appointment and then come in to the off" +
            "ice around 2 PM, after lunch.</string>\r\n  <string>I have a medical appointment t" +
            "his morning and will be working from home and leaving around 11 AM.  I’ll be in " +
            "the office around 1 PM.</string>\r\n  <string>Correction: Make that 2 PM – I need " +
            "to stop for lunch before I come in to the office.</string>\r\n  <string>I will be " +
            "leaving early today to meet a heating service technician at my house. </string>\r" +
            "\n  <string>I’ve got a bad cold, so I’m just going to head out now and grab some " +
            "lunch at home….</string>\r\n  <string>My bus service is down drivers and my normal" +
            " means of getting to work is cancelled. I can get around it by taking earlier bu" +
            "ses until the issue is resolved, I just didn\'t have forewarning today. So, I\'m W" +
            "FH.</string>\r\n  <string>I woke up with all over body aches and a fever over 102." +
            " I\'m not going to mess with the idea of being effective so I\'m taking the day to" +
            " rest, once again missing out on a delicious bagel. Sigh.</string>\r\n  <string>Ou" +
            "t sick today. Turns out I’ve got pink eye.  It’s painful to read anything so ple" +
            "ase call me if needed.</string>\r\n  <string>I’ll be working from home today since" +
            " I was coughing a lot last night and probably should have stayed home yesterday " +
            "to avoid passing it around. </string>\r\n  <string>I am currently sneezing my head" +
            " off, and in order to avoid getting everyone else sick, I’m going to work from h" +
            "ome today. </string>\r\n  <string>I’m still recuperating from a cold and will be w" +
            "orking from home again today.  I’m probably going to get off to a late start and" +
            " miss standups.</string>\r\n  <string>I’m going to work from home today. I woke up" +
            " with a stuffy nose and some sneezing.</string>\r\n  <string>I seem to have a bit " +
            "of a stomach bug. I’ll be working from home today. </string>\r\n  <string>I\'m gonn" +
            "a get my knee checked out as soon as the clinic opens (8am), hopefully I make it" +
            " back in around lunch.</string>\r\n  <string>I’m starting to feel better, but I’m " +
            "not going to be able to make it out on time today, and I would probably be late " +
            "to the meeting, so I am just going to work from home again.</string>\r\n  <string>" +
            "I will be off on a PTO day to deal with some personal stuff.</string>\r\n  <string" +
            ">I need to get over to the gym to do some physical therapy exercises, and the on" +
            "ly time I can fit this in to my schedule today before I’m too tired is 3-5 PM – " +
            "so I’ll be away from my machine during those hours.</string>\r\n  <string>There wa" +
            "s construction at my bus stop, so they have put the main line that runs by my ho" +
            "use on hold. Therefore I\'ll be WFH today.</string>\r\n  <string>I woke up with a s" +
            "ore throat and slight fever so I\'m gonna take a sick day today. Don\'t wanna get " +
            "anyone sick.</string>\r\n  <string>I\'m taking off the rest of the day. My pup has " +
            "a vet visit at 2. I\'ll have my laptop with me just in case.</string>\r\n  <string>" +
            "I will be out on vacation next week, and I need to see my doctor this afternoon." +
            " I will be leaving early at 1:30 PM.</string>\r\n  <string>Had to take an extra PT" +
            "O day today to try to get my license sorted. Additionally, as a reminder, I’ll b" +
            "e gone Wed/Thur/Fri this week.</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ExcuseList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExcuseList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentExcuse {
            get {
                return ((int)(this["CurrentExcuse"]));
            }
            set {
                this["CurrentExcuse"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</strin" +
            "g>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>" +
            "0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  " +
            "<string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</str" +
            "ing>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <strin" +
            "g>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n" +
            "  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</s" +
            "tring>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <str" +
            "ing>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>" +
            "\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0<" +
            "/string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <s" +
            "tring>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</strin" +
            "g>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>" +
            "0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  " +
            "<string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</str" +
            "ing>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <strin" +
            "g>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n" +
            "  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</s" +
            "tring>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <str" +
            "ing>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>" +
            "\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0<" +
            "/string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <s" +
            "tring>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</strin" +
            "g>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>" +
            "0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  " +
            "<string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</str" +
            "ing>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <strin" +
            "g>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n" +
            "  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</s" +
            "tring>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <str" +
            "ing>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>" +
            "\r\n  <string>0</string>\r\n  <string>0</string>\r\n  <string>0</string>\r\n</ArrayOfStr" +
            "ing>")]
        public global::System.Collections.Specialized.StringCollection ExcuseSeen {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExcuseSeen"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedTab {
            get {
                return ((int)(this["SelectedTab"]));
            }
            set {
                this["SelectedTab"] = value;
            }
        }
    }
}
